version: '3'
services:
  mongodb:
    hostname: mongodb
    image: mongo:3.0.6
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
    ports:
      - "27017:27017"
      - "28017:28017"
    networks:
      main:
        aliases:
          - elasticsearch
  elasticsearch:
     build: ./dockerfile/elasticsearch1.7.3/     
     entrypoint: ["/application/elasticsearch-1.7.3/bin/elasticsearch"]
     ports:
      - "9200:9200"
      - "9300:9300"
     networks:
      main:
        aliases:
          - mongodb
  setup:
    image: mongo:3.0.6
    links:
      - mongodb:mongodb
      - elasticsearch:elasticsearch      
    volumes:
      - ./scripts:/scripts
    entrypoint: ["bash", "/scripts/mongo_entry_point.sh"]
    networks:
      main:
        aliases:
          - mongodb


networks:
  main:
